import { PromptInput, GeneratedPrompt } from '../types';
import {
  buildContextSection,
  buildErrorSection,
  buildRootCauseSection,
  buildSelectedCodeSection,
} from '../sections/promptSections';

export function buildGenericPrompt(input: PromptInput): GeneratedPrompt {
  const content = `## Bug Report — Generated by BugMode

${buildContextSection(input)}

${buildErrorSection(input)}

${buildRootCauseSection(input)}

${buildSelectedCodeSection(input.selectedCode)}

Please analyze this error and suggest a fix.`;

  return {
    target: 'generic',
    title: `Bug: ${input.analysis.parsed.type} — ${input.analysis.parsed.message.slice(0, 60)}`,
    content,
  };
}
